In [1]:
import torch
import torch.cuda as t
import cupy as cu
import numpy as np

# Check if GPU is avail
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())

# Support both CPU and GPU, when avail

if torch.cuda.is_available():  
  dev = "cuda:0" 
  cu = cu
else:  
  dev = "cpu"  
  cu = np

device = torch.device(dev)

def gpu(t):
    return t.to(device)


gpu_cpu_test = gpu(torch.zeros(4,3))
print(gpu_cpu_test)

# Not piped to gpu
t = torch.Tensor()

# uniform number type for tensor
print(t.dtype)

# gpu or cpu?
print(t.device)

# Strided is default for how tensors are laid out in mem
print(t.layout)

GeForce RTX 2080 Ti
True
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
torch.float32
cpu
torch.strided


In [42]:
'''
#NVIDIA GPU Computing Tips with code example: 
When working with #cupy and #pytorch, you might have to do a 
couple things diff to turn a #numpy / cupy array into a tensor. 
First you need to copy the numpy (cupy )array, this will 
allocate new memory for numpy array . This is to prevent  
negative strides within Ndarray which are  the number of 
locations in memory between beginnings of successive array elements. 
Next, we flip it with the Axis in the array, which  
tells which entries are reversed. 
Lastly, we can finally convert the copied array to a tensor. 
dtypes are data type enforcement and cuda:0 is piping data to the 
GPU device which has an index of 0. This provides 7-9x speed up on 
processing in most scenarios for computer vision, and 20x speed up 
for analytics/non-machine vision applications like NLP. 
The following solution performs near 100% of the 
operations on the GPU:
'''

cupy_gpu = torch.tensor(
    cu.flip(cu.copy(
        cu.array([1,2,3,4,5,6])),
            axis=0),
            dtype=torch.float16, 
            device=dev
)

print(cupy_gpu)

tensor([6., 0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float16)


In [41]:
# CPU Bound Op
numpy_cpu = np.arange(15).reshape(3, 5)
print(numpy_cpu)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
